### ISSUE TITLE
No ARM support

### ISSUE THREAD

**Issue by NanoG6** [yegor256/squid-proxy#15]
Any workaround so this container compatible with ARM64? I have Raspberry Pi lying around @ home and this would be perfect proxy machine

`proxy The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**Comment by iloveitaly** [comment]
If you build the image locally it works fine.

@yegor256 what script/action do you use to build and push updates to this? Could we add multi-arch building?

**Comment by yegor256** [comment]
@iloveitaly this is how I build it and release: https://github.com/yegor256/squid-proxy/blob/master/.rultor.yml#L29-L35 (feel free to modify this script)

**Comment by iloveitaly** [comment]
Awesome! Rultor is new to me. Do you want to stick with Rultor or open to changing to github actions?

**Comment by yegor256** [comment]
@iloveitaly we can switch to GitHub Actions, of course

**Comment by yegor256** [comment]
@iloveitaly the workflow finished successfully: https://github.com/yegor256/squid-proxy/actions/runs/10083002355

**Comment by iloveitaly** [comment]
ARM version is working fine on my end! We can close this.

**Comment by NanoG6** [comment]
Thank you very much guys!
