### ISSUE TITLE
Access Deployed Proxy server on Heroku

### ISSUE THREAD

**Issue by kingzley** [yegor256/squid-proxy#3]
I tried deploying a fork of this repo on Heroku: https://elements.heroku.com/buttons/bynaristar/heroku-squid-proxy

But not sure how to access it.

For example in my PC I'd access proxy via curl request: 
**_`curl -x http://jeffrey:swordfish@localhost:8081  -L http://google.com`_**
This works fine.

But how can I do this after deploying to Heroku:
I tried _`**curl -x http://jeffrey:swordfish@squidi.herokuapp.com/:8081  -L http://google.com**`_
Throws invalid URL

Also tried using postman with username and password authentication in header for just http://squidi.herokuapp.com/ but still didn't work.

**Any idea on how to access proxy deployed on Heroku?**
Thanks.

**Comment by yegor256** [comment]
@kingzley I don't think that Heroku would allow you to use port 8081. Most probably you need to make sure your container responds to port 80.
